### ISSUE TITLE
Cookies are required

### ISSUE THREAD

**Issue by ishitakothari** [nageshpodilapu/Using-Facebook-Twitter-API-with-Electron-Application#1]
Hey,

I am building an electron app and integrated your code for facebook login into it. I have an error stating : 
Cookies are not enabled on your browser. Please enable cookies in your browser preferences to continue.

Please help me with this issue. Thanks!

**Comment by H4rryp0tt3r** [comment]
Electron's renderer environment doesn't come with built in support for a document.cookie API.

So, If you want to use cookies use this module [electron-cookies](https://www.npmjs.com/package/electron-cookies)

**Comment by kmligue** [comment]
I solve mine by adding this option in the BrowserWindow `'node-integration': false`. Refer to this https://github.com/electron/electron/issues/2848

**Comment by Ketan-saresa** [comment]
Hi, @ishitakothari @H4rryp0tt3r  i also faced the same issue, and i solved it by changing nodeIntegration:false,  according to the new document node-integration is not a valid identifier now.

var authWindow = new BrowserWindow({ width: 450, height: 300, webPreferences: {nodeIntegration: false, preload: __dirname + "/preload.js"} });

keep nodeIntegration under webPreferences parameter and preload for executing the script give the path of your preload.js and write window.ipc = require('ipc'); in it. After this it started working.

Another issue i m facing is i want logout functionality in my application, but FB.logout function is not available in my profile screen, is there any way to logout user ?
